### ISSUE TITLE
Don't run CI twice when merging PRs

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3oml#26]
When merging PRs, the CI is run twice (once in the branch before merging, once in main after merging). 
I don't know tick, can I switch to standard GitHub actions and set it up there?

**Comment by pat-s** [comment]
This is just how CI works in general: You can have different triggers. In this case:

- PR
- branch

If you run it in a PR and merge it into `main`, the `branch` trigger gets called which creates a build in the main branch. You want this trigger as otherwise you don't get a build for a normal commit to `main`.

Otherwise you would only need to work with PRs and never do single commits - or miss the builds for such.

{tic} is not CI, it's just a DSL for R which sits on top of a CI/CD matrix - it does not define it's triggers.

What is a bigger problem is if you would run builds for all branches as then you would get two identical builds when you're in a PR (one for the branch, one for the PR).

**Comment by pat-s** [comment]
@sebffischer (Did you eventually delete a comment? The GH shows me a comment of yours I can't see here)

So if this `if` condition you mentioned works, it would be great - this could indeed prevent a run just for this single condition.
I would even add this to the official templates in {tic} if this work.

Feel free to give it a try :)

**Comment by sebffischer** [comment]
Yes, I deleted it because it was somehow not working, but will try to fix it :)

**Comment by sebffischer** [comment]
It seems like this is currently not really possible. I can't figure out how to get the information of whether a commit resulted from a merge or whether it was a non-merge commit (except for relying on heuristics using the commit message)
